spring.application.name=multiplication
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/multiplication;AUTO_SERVER=TRUE;

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

service.gamification.host=http://localhost:8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=pshankar26
amqp.exchange.attempts=attempts.topic

spring.config.import=optional:consul:

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG
logging.level.org.springframework.amqp.rabbit.connection.CachingConnectionFactory=WARN
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#logging.level.org.springframework.amqp.rabbit.core.RabbitTemplate=DEBUG
#logging.level.org.springframework.cloud.consul.config=DEBUG
#logging.level.org.springframework.cloud.consul=DEBUG
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.root=DEBUG