spring.application.name=gamification
server.port=8081

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/gamification;AUTO_SERVER=TRUE;
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=pshankar26
amqp.exchange.attempts=attempts.topic
amqp.queue.gamification=gamification.queue

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true


logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG
logging.level.org.springframework.amqp.rabbit.connection.CachingConnectionFactory=WARN
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
#logging.level.org.springframework.amqp.rabbit.core.RabbitTemplate=DEBUG

spring.config.import=optional:consul:
spring.cloud.compatibility-verifier.enabled=false